
const products = [
    {
        id: 1,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز1.jpg',
    },
    {
        id: 2,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز2.jpg',
    },

    {
        id: 3,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز3.jpg',
    },
{
        id: 4,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز4.jpg',
    },
{
        id: 5,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز5.jpg',
    },
{
        id: 6,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز6.jpg',
    },
{        id: 7,
        name: 'Nelis',
        price:99,   
        image: '/photo/نيلز7.jpg',
    },
{        id: 8,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز8.jpg',
    },
{        id: 9,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز9.jpg',
    },
{        id: 10,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز10.jpg',
    },
{        id: 11,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز11.jpg',
    },
{        id: 12,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز12.jpg',
    },
    {
        id: 13,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز13.jpg',
    },
{
        id: 14,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز14.jpg',
    },
{
        id: 15,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز15.jpg',
    },
{        id: 16,
        name: 'Nelis',
        price:99,   
        image: '/photo/نيلز16.jpg',
    },
{        id: 17,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز17.jpg',
    },
{        id: 18,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز18.jpg',
    },
{        id: 19,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز19.jpg',
    },
    {        id: 20,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز20.jpg',
    },{        id: 21,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز21.jpg',
    },{        id: 22,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز22.jpg',
    },
    {        id: 23,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز23.jpg',
    },
     {        id: 23,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز24.jpg',
    },
     {        id: 23,
        name: 'Nelis',
        price:99,
        image: '/photo/نيلز25.jpg',
    },
]



export default products